/**
 * Landing-page marketing video configuration.
 *
 * The video shown in the hero's "Watch the overview" modal is an AI-avatar
 * presenter generated by HeyGen (see scripts/heygen/generate-landing-video.mjs
 * and docs/marketing/landing-video-script.md). The finished MP4 + poster ship as
 * committed assets under public/marketing, so the modal is on by default — no
 * build-time env var or Railway change is needed for the video to reach
 * production.
 *
 * VITE_LANDING_VIDEO_URL / VITE_LANDING_VIDEO_POSTER_URL remain optional
 * overrides: point them at a CDN / public bucket copy to serve the media from
 * there instead of the bundled files (e.g. to keep the large binary out of the
 * app's own origin).
 */

const BASE_URL = import.meta.env.BASE_URL;

// Committed assets produced by scripts/heygen/generate-landing-video.mjs.
const DEFAULT_VIDEO_SRC = `${BASE_URL}marketing/landing-overview.mp4`;
const DEFAULT_POSTER_SRC = `${BASE_URL}marketing/landing-overview-poster.jpg`;

const videoOverride = (import.meta.env.VITE_LANDING_VIDEO_URL as string | undefined)?.trim();
const posterOverride = (import.meta.env.VITE_LANDING_VIDEO_POSTER_URL as string | undefined)?.trim();

export interface LandingVideoConfig {
  /** Whether the hero shows the video modal (true) or just the animated mockup. */
  enabled: boolean;
  /** MP4 source URL — the committed asset by default, or an env override. */
  src: string;
  /** Poster image shown before playback. */
  poster?: string;
  /** WebVTT captions track, committed alongside the app for accessibility. */
  captions: string;
}

export const LANDING_VIDEO: LandingVideoConfig = {
  enabled: true,
  src: videoOverride || DEFAULT_VIDEO_SRC,
  poster: posterOverride || DEFAULT_POSTER_SRC,
  captions: `${BASE_URL}marketing/landing-overview.vtt`,
};
