/**
 * Landing-page marketing video configuration.
 *
 * The video shown in the hero's "Watch the overview" modal is an AI-avatar
 * presenter generated by HeyGen (see scripts/heygen/generate-landing-video.mjs
 * and docs/marketing/landing-video-script.md). Because that generation is a
 * deliberate, key-gated, credit-spending run-step, the landing page must not
 * depend on the finished MP4 existing at build time.
 *
 * Enablement is therefore explicit and env-driven: set VITE_LANDING_VIDEO_URL
 * to the hosted MP4 (a public bucket / CDN URL, or a committed
 * `${BASE_URL}marketing/landing-overview.mp4` path). When it is unset the hero
 * gracefully falls back to the hand-coded animated dashboard mockup and the
 * play affordance is hidden — nothing breaks.
 */

const BASE_URL = import.meta.env.BASE_URL;

const videoUrl = (import.meta.env.VITE_LANDING_VIDEO_URL as string | undefined)?.trim();
const posterUrl = (import.meta.env.VITE_LANDING_VIDEO_POSTER_URL as string | undefined)?.trim();

export interface LandingVideoConfig {
  /** Whether a video source is configured; when false the hero shows the mockup. */
  enabled: boolean;
  /** MP4 source URL (empty string when disabled). */
  src: string;
  /** Optional poster image shown before playback; undefined falls back to the video's first frame. */
  poster?: string;
  /** WebVTT captions track, committed alongside the app for accessibility. */
  captions: string;
}

export const LANDING_VIDEO: LandingVideoConfig = {
  enabled: Boolean(videoUrl),
  src: videoUrl ?? "",
  poster: posterUrl || undefined,
  captions: `${BASE_URL}marketing/landing-overview.vtt`,
};
