import { useEffect, useMemo, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { BarChart3, BookOpen, ClipboardCheck, Download, FileArchive, FileText, GraduationCap, Pill, Plus, ShieldCheck, Upload, Users } from 'lucide-react';
import { assignments as initialAssignments, complianceDisclaimer, compliancePercent, competencies, courseCategories, courses as initialCourses, externalRecords as initialExternalRecords, inservices, medications, requirements, scoreQuiz, staff } from '@/lib/caremetricData';
import { buildComplianceBinderHtml, downloadTextFile, openPrintablePdf, toCsv } from '@/lib/caremetricExports';
import { runCareMetricAi } from '@/lib/caremetricAi';
import { fetchCareMetricPayload, type CareMetricPayload } from '@/lib/caremetricApi';

function statusTone(status: string) {
  if (['complete','completed','approved','current','pass','published'].includes(status)) return 'bg-emerald-100 text-emerald-800';
  if (['due_soon','pending','in progress','draft'].includes(status)) return 'bg-amber-100 text-amber-800';
  if (['overdue','expired','failed'].includes(status)) return 'bg-red-100 text-red-800';
  return 'bg-slate-100 text-slate-800';
}
function ExportButtons({ name, rows = [] }: { name: string; rows?: Record<string, string | number | boolean | null | undefined>[] }) {
  const exportRows = rows.length > 0 ? rows : [{ report: name, generatedAt: new Date().toISOString(), status: 'ready' }];
  return <div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => downloadTextFile(`${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.csv`, toCsv(exportRows), 'text/csv')}><Download className="h-4 w-4 mr-2"/>CSV</Button><Button variant="outline" size="sm" onClick={() => openPrintablePdf(buildComplianceBinderHtml({ organization: 'Demo Care Group', facility: 'All Facilities', dateRange: '2026 YTD', sections: [name], generatedAt: new Date().toLocaleString(), summary: `${name} export generated from CareMetric Train.` }))}><FileText className="h-4 w-4 mr-2"/>PDF</Button><span className="sr-only">Export {name}</span></div>;
}

export default function CareMetricModules({ initialTab = 'dashboard' }: { initialTab?: string }) {
  const [activeTab, setActiveTab] = useState(initialTab);
  const [search, setSearch] = useState('');
  const [courses, setCourses] = useState(initialCourses);
  const [assignments, setAssignments] = useState(initialAssignments);
  const [externalRecords, setExternalRecords] = useState(initialExternalRecords);
  const [activity, setActivity] = useState<string[]>(['Demo tenant loaded', 'Audit log initialized']);
  const [aiMessage, setAiMessage] = useState('');
  const [apiPayload, setApiPayload] = useState<CareMetricPayload | null>(null);
  const [apiError, setApiError] = useState('');
  const filteredStaff = useMemo(() => staff.filter(s => `${s.name} ${s.role} ${s.facility}`.toLowerCase().includes(search.toLowerCase())), [search]);
  const quiz = scoreQuiz([true, true, false, true, true], 80);
  const compliance = compliancePercent(staff);
  useEffect(() => {
    fetchCareMetricPayload()
      .then(payload => { setApiPayload(payload); setApiError(''); })
      .catch(error => setApiError(error instanceof Error ? error.message : 'Unable to load API-backed CareMetric data'));
  }, []);
  const addActivity = (message: string) => setActivity(current => [`${new Date().toLocaleTimeString()} — ${message}`, ...current].slice(0, 8));
  const publishCourse = () => { const next = { ...courses[0], id: `c${courses.length + 1}`, title: `Custom annual training ${courses.length + 1}`, category: 'Annual In-Service Training', version: '0.1-draft', status: 'draft', completions: 0, tags: ['custom'] }; setCourses(current => [next, ...current]); addActivity(`Course draft created: ${next.title}`); };
  const completeFirstAssignment = () => { setAssignments(current => current.map((assignment, index) => index === 0 ? { ...assignment, status: 'completed', score: 96 } : assignment)); addActivity('Learner completed assigned course; certificate generated'); };
  const approveFirstExternal = () => { setExternalRecords(current => current.map((record, index) => index === 0 ? { ...record, status: 'approved' } : record)); addActivity('External certificate approved with audit trail'); };
  const generateBinder = () => { const ok = openPrintablePdf(buildComplianceBinderHtml({ organization: 'Demo Care Group', facility: 'Oakview Personal Care', dateRange: '2026-01-01 to 2026-12-31', sections: ['Dashboard', 'Staff training matrix', 'Medication administration', 'Competencies', 'External certificates', 'In-service attendance'], generatedAt: new Date().toLocaleString(), summary: `${compliance}% compliant with ${assignments.filter(a => a.status === 'overdue').length} overdue assignment(s).` })); addActivity(ok ? 'Compliance Binder PDF opened for printing' : 'Popup blocked while opening Compliance Binder'); };
  return <div className="space-y-6">
    <div className="rounded-2xl bg-gradient-to-br from-cyan-950 via-slate-900 to-emerald-950 p-7 text-white shadow-lg">
      <div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between">
        <div><p className="text-sm uppercase tracking-[0.25em] text-cyan-200">CareMetric Train</p>{apiPayload ? <p className="mt-2 text-xs text-emerald-100">API connected · {apiPayload.summary.coursesTotal} courses · {apiPayload.summary.pendingExternalReviews} pending reviews</p> : apiError ? <p className="mt-2 text-xs text-amber-100">Using demo fallback data · {apiError}</p> : <p className="mt-2 text-xs text-cyan-100">Loading API-backed tenant data…</p>}<h1 className="text-3xl font-bold mt-2">Healthcare LMS & compliance command center</h1><p className="mt-3 max-w-3xl text-cyan-50/80">Original MVP for personal care homes, assisted living providers, trainers, learners, auditors, and SaaS super admins. Manage assignments, quizzes, certificates, medication documentation, competencies, in-services, reports, packages, and audit trails.</p></div>
        <div className="grid grid-cols-2 gap-3 min-w-[280px]"><Card><CardContent className="p-4 text-slate-900"><div className="text-2xl font-bold">{compliance}%</div><div className="text-xs text-muted-foreground">Org compliance</div></CardContent></Card><Card><CardContent className="p-4 text-slate-900"><div className="text-2xl font-bold">{assignments.filter(a=>a.status==='overdue').length}</div><div className="text-xs text-muted-foreground">Overdue</div></CardContent></Card></div>
      </div>
    </div>
    <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4">
      <TabsList className="flex h-auto flex-wrap justify-start"><TabsTrigger value="dashboard">Dashboards</TabsTrigger><TabsTrigger value="courses">Courses</TabsTrigger><TabsTrigger value="assignments">Assignments</TabsTrigger><TabsTrigger value="compliance">Compliance</TabsTrigger><TabsTrigger value="meds">Medication</TabsTrigger><TabsTrigger value="competencies">Competencies</TabsTrigger><TabsTrigger value="inservice">In-Service</TabsTrigger><TabsTrigger value="external">External Certs</TabsTrigger><TabsTrigger value="reports">Reports</TabsTrigger><TabsTrigger value="settings">Settings</TabsTrigger></TabsList>
      <TabsContent value="dashboard"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[{t:'Learners',v:staff.length,i:Users},{t:'Published courses',v:courses.filter(c=>c.status==='published').length,i:BookOpen},{t:'Annual hours',v:staff.reduce((a,s)=>a+s.hours,0),i:GraduationCap},{t:'Survey readiness',v:'86%',i:ShieldCheck}].map(x=>{const I=x.i;return <Card key={x.t}><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-sm">{x.t}</CardTitle><I className="h-4 w-4 text-muted-foreground"/></CardHeader><CardContent><div className="text-2xl font-bold">{x.v}</div><Progress value={typeof x.v==='number'?Math.min(Number(x.v)*12,100):86} className="mt-3"/></CardContent></Card>})}</div><Card className="mt-4"><CardHeader><CardTitle>Facility compliance</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Staff</TableHead><TableHead>Role</TableHead><TableHead>Facility</TableHead><TableHead>Compliance</TableHead><TableHead>Medication</TableHead></TableRow></TableHeader><TableBody>{staff.map(s=><TableRow key={s.id}><TableCell>{s.name}</TableCell><TableCell>{s.role}</TableCell><TableCell>{s.facility}</TableCell><TableCell><div className="flex items-center gap-2"><Progress value={s.compliance} className="w-24" />{s.compliance}%</div></TableCell><TableCell><Badge className={statusTone(s.med)}>{s.med.replace('_',' ')}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="courses"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Course catalog and builder</CardTitle><Button onClick={publishCourse}><Plus className="h-4 w-4 mr-2"/>Create course</Button></CardHeader><CardContent><div className="mb-4 flex flex-wrap gap-2">{courseCategories.map(c=><Badge variant="outline" key={c}>{c}</Badge>)}</div><Table><TableHeader><TableRow><TableHead>Course</TableHead><TableHead>Category</TableHead><TableHead>Type</TableHead><TableHead>Version</TableHead><TableHead>Hours</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{courses.map(c=><TableRow key={c.id}><TableCell><div className="font-medium">{c.title}</div><div className="text-xs text-muted-foreground">Passing score {c.pass ?? 'n/a'} · certificate eligible · tags {c.tags.join(', ')}</div></TableCell><TableCell>{c.category}</TableCell><TableCell>{c.type}</TableCell><TableCell>{c.version}</TableCell><TableCell>{c.hours}</TableCell><TableCell><Badge className={statusTone(c.status)}>{c.status}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="assignments"><Card><CardHeader><CardTitle>Assignment workflow, learner course taking, and quiz engine</CardTitle></CardHeader><CardContent><div className="mb-4 grid gap-3 md:grid-cols-3"><Input placeholder="Search staff" value={search} onChange={e=>setSearch(e.target.value)} /><Button onClick={() => { setAssignments(current => [{ staff: filteredStaff[0]?.name ?? 'New learner', course: courses[0].title, due: '2026-08-15', status: 'not started', score: null }, ...current]); addActivity('Course assigned by role/facility workflow'); }}>Assign by role/facility</Button><Button variant="outline" onClick={completeFirstAssignment}>Complete + certificate</Button></div><Table><TableHeader><TableRow><TableHead>Staff</TableHead><TableHead>Course</TableHead><TableHead>Due</TableHead><TableHead>Status</TableHead><TableHead>Quiz</TableHead></TableRow></TableHeader><TableBody>{assignments.map((a,i)=><TableRow key={i}><TableCell>{a.staff}</TableCell><TableCell>{a.course}</TableCell><TableCell>{a.due}</TableCell><TableCell><Badge className={statusTone(a.status)}>{a.status}</Badge></TableCell><TableCell>{a.score ?? 'not attempted'} {a.score && a.score>=80 ? 'pass' : ''}</TableCell></TableRow>)}</TableBody></Table><p className="mt-3 text-sm text-muted-foreground">Sample quiz attempt: {quiz.score}% — {quiz.passed ? 'passing quiz marks course complete and certificate-ready' : 'retake required'}.</p></CardContent></Card></TabsContent>
      <TabsContent value="compliance"><Card><CardHeader><CardTitle>Configurable PA personal care home sample requirements</CardTitle></CardHeader><CardContent><p className="rounded-lg border bg-amber-50 p-3 text-sm text-amber-900 mb-4">{complianceDisclaimer}</p><Table><TableHeader><TableRow><TableHead>Requirement</TableHead><TableHead>Roles</TableHead><TableHead>Hours</TableHead><TableHead>Renewal</TableHead><TableHead>Evidence</TableHead></TableRow></TableHeader><TableBody>{requirements.map(r=><TableRow key={r.name}><TableCell><div className="font-medium">{r.name}</div><div className="text-xs text-muted-foreground">{r.citation}</div></TableCell><TableCell>{r.roles.join(', ')}</TableCell><TableCell>{r.hours}</TableCell><TableCell>{r.renewal}</TableCell><TableCell>{r.evidence.join(', ')}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="meds"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle><Pill className="inline h-5 w-5 mr-2"/>Medication administration tracking</CardTitle><ExportButtons name="medication" rows={medications.map(m => ({ staff: m.staff, expiration: m.expiration, status: m.status, documentation: m.docs }))}/></CardHeader><CardContent><Table><TableBody>{medications.map(m=><TableRow key={m.staff}><TableCell>{m.staff}</TableCell><TableCell>Original {m.original}</TableCell><TableCell>Renewal {m.renewal}</TableCell><TableCell>Expiration {m.expiration}</TableCell><TableCell>{m.trainer}</TableCell><TableCell><Badge className={statusTone(m.status)}>{m.status.replace('_',' ')}</Badge></TableCell><TableCell>{m.docs?'docs on file':'missing documentation'}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="competencies"><Card><CardHeader><CardTitle><ClipboardCheck className="inline h-5 w-5 mr-2"/>Competency checklists</CardTitle></CardHeader><CardContent><Table><TableBody>{competencies.map(c=><TableRow key={`${c.template}-${c.staff}`}><TableCell>{c.template}</TableCell><TableCell>{c.staff}</TableCell><TableCell>{c.observedBy}</TableCell><TableCell>{c.date}</TableCell><TableCell><Badge className={statusTone(c.result)}>{c.result}</Badge></TableCell><TableCell>Re-observe {c.reobserve}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="inservice"><Card><CardHeader><CardTitle>Live in-service sessions</CardTitle></CardHeader><CardContent><Table><TableBody>{inservices.map(s=><TableRow key={s.title}><TableCell>{s.title}</TableCell><TableCell>{s.instructor}</TableCell><TableCell>{s.facility}</TableCell><TableCell>{s.when}</TableCell><TableCell>{s.hours} hrs</TableCell><TableCell>{s.complete}/{s.attendees} complete</TableCell><TableCell><Button size="sm">Mark attendance</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="external"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle><Upload className="inline h-5 w-5 mr-2"/>External training review</CardTitle><Button onClick={() => { setExternalRecords(current => [{ name: 'Uploaded outside dementia-care certificate', staff: 'Jordan Smith', issuer: 'External provider', completed: '2026-07-04', expires: '2027-07-04', hours: 1, status: 'pending' }, ...current]); addActivity('External certificate uploaded for review'); }}><Upload className="h-4 w-4 mr-2"/>Upload certificate</Button></CardHeader><CardContent><Table><TableBody>{externalRecords.map(r=><TableRow key={r.name}><TableCell>{r.name}</TableCell><TableCell>{r.staff}</TableCell><TableCell>{r.issuer}</TableCell><TableCell>{r.completed}</TableCell><TableCell>{r.expires}</TableCell><TableCell>{r.hours} hrs</TableCell><TableCell><Badge className={statusTone(r.status)}>{r.status}</Badge></TableCell><TableCell><Button size="sm" variant="outline" onClick={approveFirstExternal}>Approve / reject</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent>
      <TabsContent value="reports"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle><BarChart3 className="inline h-5 w-5 mr-2"/>Survey-ready reports and Compliance Binder</CardTitle><Button onClick={generateBinder}><FileArchive className="h-4 w-4 mr-2"/>Generate Binder PDF</Button></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{['Staff Training Summary by Facility','Overdue Training Report','Annual Training Hours Report','Medication Administration Certification Report','Direct Care Staff Training Report','Administrator Training Report','Competency Checklist Report','External Certificates Report','In-Service Attendance Report','Missing Documentation Report','Expiring Certifications Report','Full Facility Compliance Binder Export'].map(r=><div className="rounded-lg border p-4" key={r}><div className="font-medium">{r}</div><div className="mt-3"><ExportButtons name={r} rows={staff.map(s => ({ staff: s.name, facility: s.facility, compliance: s.compliance, overdue: s.overdue }))}/></div></div>)}</div></CardContent></Card></TabsContent>
      <TabsContent value="settings"><Card><CardHeader><CardTitle>Admin settings, packages, AI-ready tools, and audit logs</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border p-4"><h3 className="font-semibold">Packages</h3><p>Starter, Compliance Plus, and Enterprise with trial/active/past due/canceled/suspended status fields and Stripe-ready structure.</p></div><div className="rounded-lg border p-4"><h3 className="font-semibold">AI-assisted placeholders</h3><p>Course outline, quiz generator, policy-to-training converter, gap explanation, survey summary, and plan recommendations show friendly unavailable messages without API keys.</p><Button className="mt-3" variant="outline" onClick={() => { const result = runCareMetricAi('survey_summary', 'Summarize current compliance gaps'); setAiMessage(result.message); addActivity('AI-ready survey summary requested'); }}>Try AI summary</Button>{aiMessage && <p className="mt-2 text-sm text-muted-foreground">{aiMessage}</p>}</div><div className="rounded-lg border p-4"><h3 className="font-semibold">Tenant security</h3><p>Role-based screens for super admin, org admin, facility admin, trainer, learner, and auditor/read-only workflows.</p></div><div className="rounded-lg border p-4"><h3 className="font-semibold">Audit events</h3><p>Logs major actions: login, invites, role changes, course publishing, assignments, completions, certificates, waivers, exports, uploads, and approvals.</p><ul className="mt-3 space-y-1 text-sm text-muted-foreground">{activity.map(item => <li key={item}>{item}</li>)}</ul></div></CardContent></Card></TabsContent>
    </Tabs>
  </div>
}

export function CareMetricCoursesPage() { return <CareMetricModules initialTab="courses" />; }
export function CareMetricAssignmentsPage() { return <CareMetricModules initialTab="assignments" />; }
export function CareMetricCompliancePage() { return <CareMetricModules initialTab="compliance" />; }
export function CareMetricMedicationPage() { return <CareMetricModules initialTab="meds" />; }
export function CareMetricCompetenciesPage() { return <CareMetricModules initialTab="competencies" />; }
export function CareMetricInservicePage() { return <CareMetricModules initialTab="inservice" />; }
export function CareMetricExternalRecordsPage() { return <CareMetricModules initialTab="external" />; }
export function CareMetricReportsPage() { return <CareMetricModules initialTab="reports" />; }
export function CareMetricSettingsPage() { return <CareMetricModules initialTab="settings" />; }
