import { useRef } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";

type PackageReceipt = { operationId: string; packageId: string; versionId: string; status: "pending" | "accepted";
  sourceRevision: string; sourceSha256: string; runtimeSha256: string | null; entryPoint: string | null };
// These RPCs are generated by the same migration. Keep the transport independent
// of generated-type ordering while its isolated database lane regenerates types.
const rpc = () => supabase as unknown as { rpc: (name: string, args: Record<string, unknown>) => Promise<{ data: unknown; error: { message: string } | null }> };
const digest = async (file: File) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", await file.arrayBuffer())))
  .map(byte => byte.toString(16).padStart(2, "0")).join("");
export function useUploadLearningPackage() {
  const queryClient = useQueryClient();
  const attempts = useRef(new Map<string, { requestId: string; sourceRevision: string }>());
  return useMutation({ mutationFn: async ({ file, versionId, standard = "scorm_1_2" }: { file: File; versionId: string; standard?: "scorm_1_2" | "scorm_2004_4th" | "xapi" }): Promise<PackageReceipt> => {
    if (!file.name.toLowerCase().endsWith(".zip") || file.size < 1 || file.size > 50 * 1024 * 1024) throw new Error("Choose a ZIP package no larger than 50 MB.");
    const sourceSha256 = await digest(file); const key = `${versionId}:${standard}:${sourceSha256}`;
    let attempt = attempts.current.get(key);
    if (attempt) {
      // A new authenticated session may read this actor's durable receipt without
      // replaying the old session's write authority or uploading another object.
      const prior = await rpc().rpc("get_native_learning_package_operation", { p_request_id: attempt.requestId });
      if (prior.error) throw new Error(prior.error.message);
      const status = prior.data as { status?: string; result?: PackageReceipt } | null;
      if (status?.status === "committed" && status.result?.versionId === versionId && status.result.sourceSha256 === sourceSha256) return status.result;
      if (status?.status === "expired") { attempts.current.delete(key); attempt = undefined; }
    }
    if (!attempt) {
      const context = await rpc().rpc("get_native_learning_package_context", { p_version_id: versionId, p_package_id: null });
      if (context.error) throw new Error(context.error.message);
      const source = context.data as { versionId?: string; sourceRevision?: string };
      if (source.versionId !== versionId || !/^[0-9a-f]{64}$/.test(source.sourceRevision ?? "")) throw new Error("Refresh the course draft before uploading.");
      attempt = { requestId: crypto.randomUUID(), sourceRevision: source.sourceRevision! }; attempts.current.set(key, attempt);
    }
    const form = new FormData();
    form.set("request", JSON.stringify({ operation: "upload", requestId: attempt.requestId, versionId, sourceRevision: attempt.sourceRevision,
      reason: "Upload original package for this course draft", standard, sourceSha256, sourceBytes: file.size }));
    form.set("file", file);
    const response = await supabase.functions.invoke("ingest-learning-package", { body: form });
    if (response.error) throw new Error("Package upload did not finish. Retry this file to check its saved receipt.");
    const receipt = response.data as PackageReceipt & { error?: string };
    if (receipt?.error) throw new Error(receipt.error);
    if (receipt?.versionId !== versionId || receipt.sourceSha256 !== sourceSha256 || receipt.status !== "pending"
      || typeof receipt.packageId !== "string" || !/^[0-9a-f-]{36}$/i.test(receipt.packageId)) throw new Error("The package receipt could not be verified.");
    return receipt;
  }, onSuccess: () => {
    void queryClient.invalidateQueries({ queryKey: ["learning_packages"] });
    void queryClient.invalidateQueries({ queryKey: ["learning_authoring_dependencies"] });
    void queryClient.invalidateQueries({ queryKey: ["governed_draft_source"] });
    void queryClient.invalidateQueries({ queryKey: ["learning_package_context"] });
  } });
}
