import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import type{Json,Tables}from"@/lib/database.types";
export type QapiProject=Tables<"qapi_projects">;
export interface QapiProjectView extends QapiProject{facility:{id:string;name:string}|null;lead:{id:string;first_name:string;last_name:string}|null;actions:{id:string;action_type:string;work_item_id:string}[]}
const sel="*,facility:facilities(id,name),lead:profiles!qapi_projects_project_lead_profile_id_fkey(id,first_name,last_name),actions:qapi_action_items(id,action_type,work_item_id)";
const inv=(q:ReturnType<typeof useQueryClient>)=>{q.invalidateQueries({queryKey:["qapi"]});q.invalidateQueries({queryKey:["work-items"]})};
export function useListQapiProjects(f:{organizationId?:string;facilityId?:string;status?:string}={}){return useQuery({queryKey:["qapi","projects",f],queryFn:async()=>{let q=supabase.from("qapi_projects").select(sel).order("target_completion_date");if(f.organizationId)q=q.eq("organization_id",f.organizationId);if(f.facilityId)q=q.eq("facility_id",f.facilityId);if(f.status)q=q.eq("status",f.status);const{data,error}=await q;if(error)throw error;return data as unknown as QapiProjectView[]}})}
export function useGetQapiProject(id?:string){return useQuery({queryKey:["qapi","project",id],queryFn:async()=>{const{data,error}=await supabase.from("qapi_projects").select(sel).eq("id",id!).single();if(error)throw error;return data as unknown as QapiProjectView},enabled:!!id})}
export function useQapiProjectActivity(id?:string){return useQuery({queryKey:["qapi","activity",id],queryFn:async()=>{const[m,notes,h,a]=await Promise.all([supabase.from("qapi_measurements").select("*").eq("project_id",id!).order("period_end",{ascending:false}),supabase.from("qapi_meeting_notes").select("*").eq("project_id",id!).order("held_at",{ascending:false}),supabase.from("qapi_project_history").select("*").eq("project_id",id!).order("occurred_at",{ascending:false}),supabase.from("qapi_action_items").select("*,work_item:work_items(*)").eq("project_id",id!)]);const e=[m,notes,h,a].find(x=>x.error)?.error;if(e)throw e;return{measurements:m.data??[],meetings:notes.data??[],history:h.data??[],actions:a.data??[]}},enabled:!!id})}
export function useQapiSourceMetrics(facilityId?:string,from?:string,through?:string){return useQuery({queryKey:["qapi","metrics",facilityId,from,through],queryFn:async()=>{const{data,error}=await supabase.rpc("get_qapi_source_metrics",{p_facility_id:facilityId!,p_from:from!,p_through:through!});if(error)throw error;return data as Record<string,unknown>},enabled:!!facilityId&&!!from&&!!through})}
export function useCreateQapiProject(){const q=useQueryClient();return useMutation({mutationFn:async(i:{facilityId:string;title:string;problem:string;source:string;baseline:string;objective:string;target:string;targetValue?:number;completion:string;lead:string;sourceType?:string;sourceId?:string})=>{const{data,error}=await supabase.rpc("create_qapi_project" as never,{p_facility_id:i.facilityId,p_title:i.title,p_problem_statement:i.problem,p_source_of_concern:i.source,p_baseline_data:i.baseline,p_measurable_objective:i.objective,p_target_description:i.target,p_target_value:i.targetValue??null,p_target_completion_date:i.completion,p_project_lead:i.lead,p_source_type:i.sourceType??null,p_source_id:i.sourceId??null}as never);if(error)throw error;return data as string},onSuccess:()=>inv(q)})}
export function useUpdateQapiPlan(){const q=useQueryClient();return useMutation({mutationFn:async(i:{id:string;status:string;team:Json;method:string;root:string;interventions:string;frequency:string;sample:string;barriers:string;adjustments:string;effectiveness:string;sustainment:string;reason:string})=>{const{data,error}=await supabase.rpc("update_qapi_project_plan",{p_project_id:i.id,p_status:i.status,p_team_members:i.team,p_root_cause_method:i.method,p_root_cause_analysis:i.root,p_planned_interventions:i.interventions,p_measurement_frequency:i.frequency,p_audit_sample:i.sample,p_barriers:i.barriers,p_adjustments:i.adjustments,p_effectiveness:i.effectiveness,p_sustainment:i.sustainment,p_reason:i.reason});if(error)throw error;return data},onSuccess:()=>inv(q)})}
export function useAddQapiAction(){const q=useQueryClient();return useMutation({mutationFn:async(i:{id:string;title:string;description:string;type:string;owner:string;due:string})=>{const{data,error}=await supabase.rpc("add_qapi_action",{p_project_id:i.id,p_title:i.title,p_description:i.description,p_action_type:i.type,p_owner:i.owner,p_due_at:i.due});if(error)throw error;return data},onSuccess:()=>inv(q)})}
export function useRecordQapiMeasurement(){const q=useQueryClient();return useMutation({mutationFn:async(i:{id:string;start:string;end:string;numerator:number;denominator?:number;notes:string;sample:string})=>{const{data,error}=await supabase.rpc("record_qapi_measurement" as never,{p_project_id:i.id,p_start:i.start,p_end:i.end,p_numerator:i.numerator,p_denominator:i.denominator??null,p_notes:i.notes,p_sample:i.sample}as never);if(error)throw error;return data},onSuccess:()=>inv(q)})}
export function useAddQapiMeeting(){const q=useQueryClient();return useMutation({mutationFn:async(i:{id:string;held:string;attendees:string;notes:string;barriers:string;adjustments:string})=>{const{data,error}=await supabase.rpc("add_qapi_meeting_note",{p_project_id:i.id,p_held_at:i.held,p_attendees:i.attendees,p_notes:i.notes,p_barriers:i.barriers,p_adjustments:i.adjustments});if(error)throw error;return data},onSuccess:()=>inv(q)})}
