create extension if not exists pgcrypto with schema extensions;
create table public.saved_report_definitions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,report_type text not null check(report_type in ('compliance','qualification','delivery','schedule','remediation','incident','policy','binder')),owner_profile_id uuid references public.profiles(id),current_version_id uuid,audience_roles text[] not null default array[]::text[],retention_days integer not null default 2555 check(retention_days between 1 and 36500),entitlement_key text,schedule_enabled boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.saved_report_versions(id uuid primary key default gen_random_uuid(),report_definition_id uuid not null references public.saved_report_definitions(id) on delete cascade,organization_id uuid not null references public.organizations(id) on delete cascade,version_number integer not null,filters jsonb not null default '{}',columns jsonb not null default '[]',sort_spec jsonb not null default '[]',time_zone text not null default 'UTC',configuration_sha256 text not null check(configuration_sha256 ~ '^[0-9a-f]{64}$'),state text not null default 'draft' check(state in ('draft','published','superseded','retired')),created_by uuid references public.profiles(id),published_at timestamptz,created_at timestamptz not null default now(),unique(report_definition_id,version_number));
alter table public.saved_report_definitions add constraint saved_report_current_version_fk foreign key(current_version_id) references public.saved_report_versions(id) on delete restrict;
create table public.report_schedules(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,report_definition_id uuid not null references public.saved_report_definitions(id) on delete cascade,report_version_id uuid not null references public.saved_report_versions(id) on delete restrict,cron_expression text not null,time_zone text not null,delivery_mode text not null check(delivery_mode in ('in_app','email_link','evidence_room')),audience jsonb not null,retention_days integer not null,enabled boolean not null default true,next_run_at timestamptz,last_run_at timestamptz,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.report_snapshots(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid references public.facilities(id),report_definition_id uuid not null references public.saved_report_definitions(id) on delete restrict,report_version_id uuid not null references public.saved_report_versions(id) on delete restrict,as_of timestamptz not null,configuration jsonb not null,configuration_sha256 text not null check(configuration_sha256 ~ '^[0-9a-f]{64}$'),source_watermarks jsonb not null default '{}',included_record_ids jsonb not null check(jsonb_typeof(included_record_ids)='object'),row_counts jsonb not null check(jsonb_typeof(row_counts)='object'),material_totals jsonb not null default '{}',reconciliation_status text not null check(reconciliation_status in ('pending','reconciled','variance','failed')),reconciliation_detail jsonb not null default '{}',snapshot_sha256 text not null check(snapshot_sha256 ~ '^[0-9a-f]{64}$'),status text not null default 'ready' check(status in ('generating','ready','failed','withdrawn')),generated_by uuid references public.profiles(id),generated_at timestamptz not null default now(),unique(report_version_id,as_of,configuration_sha256));
create table public.report_snapshot_artifacts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid references public.facilities(id),snapshot_id uuid not null references public.report_snapshots(id) on delete restrict,artifact_type text not null check(artifact_type in ('csv','pdf','binder','json_manifest')),storage_bucket text not null,storage_path text not null,content_sha256 text not null check(content_sha256 ~ '^[0-9a-f]{64}$'),byte_size bigint not null check(byte_size>0),watermark_template text,manifest jsonb not null,created_at timestamptz not null default now(),withdrawn_at timestamptz,unique(snapshot_id,artifact_type));
create table public.historical_metric_snapshots(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid references public.facilities(id),metric_domain text not null check(metric_domain in ('compliance','qualification','delivery','schedule','remediation','incident','policy')),dimension_version jsonb not null,period_start date not null,period_end date not null,metrics jsonb not null,source_snapshot_id uuid references public.report_snapshots(id) on delete restrict,metrics_sha256 text not null check(metrics_sha256 ~ '^[0-9a-f]{64}$'),created_at timestamptz not null default now(),unique nulls not distinct(organization_id,facility_id,metric_domain,period_start,period_end));

create table public.evidence_collections(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),name text not null,purpose text not null,status text not null default 'draft' check(status in ('draft','published','closed','withdrawn')),legal_hold boolean not null default false,terms_version text not null,created_by uuid references public.profiles(id),published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.evidence_collection_artifacts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),collection_id uuid not null references public.evidence_collections(id) on delete cascade,snapshot_artifact_id uuid not null references public.report_snapshot_artifacts(id) on delete restrict,display_name text not null,artifact_scope jsonb not null default '{}',added_by uuid references public.profiles(id),added_at timestamptz not null default now(),withdrawn_at timestamptz,unique(collection_id,snapshot_artifact_id));
create table public.evidence_guest_grants(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),collection_id uuid not null references public.evidence_collections(id) on delete cascade,token_sha256 text not null unique check(token_sha256 ~ '^[0-9a-f]{64}$'),guest_label text not null,guest_email_hash text,allowed_artifact_ids uuid[] not null,expires_at timestamptz not null,terms_version text not null,accepted_at timestamptz,step_up_required boolean not null default false,step_up_verified_at timestamptz,revoked_at timestamptz,revoked_by uuid references public.profiles(id),revocation_reason text,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),last_reviewed_at timestamptz,check(expires_at>created_at));
create table public.evidence_guest_access_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),guest_grant_id uuid references public.evidence_guest_grants(id) on delete restrict,collection_id uuid not null references public.evidence_collections(id) on delete restrict,artifact_id uuid references public.evidence_collection_artifacts(id) on delete restrict,event_type text not null check(event_type in ('view','download','comment','share','denied','revoked','withdrawn','terms_accepted')),request_fingerprint_sha256 text,reason text not null,occurred_at timestamptz not null default now());
create table public.evidence_guest_comments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),collection_id uuid not null references public.evidence_collections(id) on delete cascade,artifact_id uuid references public.evidence_collection_artifacts(id),guest_grant_id uuid not null references public.evidence_guest_grants(id),body text not null check(length(btrim(body)) between 1 and 5000),created_at timestamptz not null default now());

create or replace function public.record_report_snapshot(p_report_version_id uuid,p_facility_id uuid,p_as_of timestamptz,p_source_watermarks jsonb,p_record_ids jsonb,p_row_counts jsonb,p_material_totals jsonb,p_reconciliation_status text,p_reconciliation_detail jsonb)
returns uuid language plpgsql security definer set search_path='' as $$declare v public.saved_report_versions%rowtype;v_id uuid;v_body jsonb;begin if coalesce(auth.jwt()->>'role','')<>'service_role' then raise exception 'Only the trusted report worker may record snapshots' using errcode='42501';end if;select * into v from public.saved_report_versions where id=p_report_version_id and state in('published','superseded');if not found then raise exception 'Published report version not found' using errcode='P0002';end if;v_body:=jsonb_build_object('version',v.id,'asOf',p_as_of,'config',jsonb_build_object('filters',v.filters,'columns',v.columns,'sort',v.sort_spec,'timeZone',v.time_zone),'watermarks',p_source_watermarks,'records',p_record_ids,'rowCounts',p_row_counts,'totals',p_material_totals);insert into public.report_snapshots(organization_id,facility_id,report_definition_id,report_version_id,as_of,configuration,configuration_sha256,source_watermarks,included_record_ids,row_counts,material_totals,reconciliation_status,reconciliation_detail,snapshot_sha256,status)values(v.organization_id,p_facility_id,v.report_definition_id,v.id,p_as_of,v_body->'config',v.configuration_sha256,p_source_watermarks,p_record_ids,p_row_counts,p_material_totals,p_reconciliation_status,p_reconciliation_detail,encode(extensions.digest(convert_to(v_body::text,'utf8'),'sha256'),'hex'),'ready')on conflict(report_version_id,as_of,configuration_sha256) do nothing returning id into v_id;if v_id is null then select id into v_id from public.report_snapshots where report_version_id=v.id and as_of=p_as_of and configuration_sha256=v.configuration_sha256;end if;return v_id;end$$;

create or replace function public.issue_evidence_guest_grant(p_collection_id uuid,p_guest_label text,p_guest_email_hash text,p_allowed_artifact_ids uuid[],p_expires_at timestamptz,p_step_up boolean)
returns jsonb language plpgsql security definer set search_path='' as $$declare v public.evidence_collections%rowtype;v_raw text;v_id uuid;begin select * into v from public.evidence_collections where id=p_collection_id and status='published';if not found then raise exception 'Published evidence collection not found' using errcode='P0002';end if;perform app_private.assert_phase5_manager(v.organization_id,v.facility_id);if p_expires_at<=now() or p_expires_at>now()+interval '90 days' or exists(select 1 from unnest(p_allowed_artifact_ids) a where not exists(select 1 from public.evidence_collection_artifacts e where e.id=a and e.collection_id=v.id and e.facility_id=v.facility_id and e.withdrawn_at is null)) then raise exception 'Guest grant scope or expiration is invalid' using errcode='22023';end if;v_raw:=encode(extensions.gen_random_bytes(32),'hex');insert into public.evidence_guest_grants(organization_id,facility_id,collection_id,token_sha256,guest_label,guest_email_hash,allowed_artifact_ids,expires_at,terms_version,step_up_required,created_by)values(v.organization_id,v.facility_id,v.id,encode(extensions.digest(convert_to(v_raw,'utf8'),'sha256'),'hex'),p_guest_label,p_guest_email_hash,p_allowed_artifact_ids,p_expires_at,v.terms_version,p_step_up,auth.uid())returning id into v_id;return jsonb_build_object('grantId',v_id,'token',v_raw,'expiresAt',p_expires_at);end$$;

create or replace function public.authorize_evidence_guest_artifact(p_token text,p_artifact_id uuid,p_event_type text,p_fingerprint text default null)
returns jsonb language plpgsql security definer set search_path='' as $$declare v_grant public.evidence_guest_grants%rowtype;v_art public.evidence_collection_artifacts%rowtype;v_org public.organizations%rowtype;v_allowed boolean;v_reason text;begin if p_event_type not in ('view','download','comment','share') then raise exception 'Invalid guest event type' using errcode='22023';end if;select * into v_grant from public.evidence_guest_grants where token_sha256=encode(extensions.digest(convert_to(p_token,'utf8'),'sha256'),'hex');select * into v_art from public.evidence_collection_artifacts where id=p_artifact_id;select * into v_org from public.organizations where id=v_grant.organization_id;v_allowed:=v_grant.id is not null and v_art.id is not null and v_art.collection_id=v_grant.collection_id and v_art.facility_id=v_grant.facility_id and p_artifact_id=any(v_grant.allowed_artifact_ids) and v_grant.revoked_at is null and v_grant.expires_at>now() and v_grant.accepted_at is not null and (not v_grant.step_up_required or v_grant.step_up_verified_at is not null) and v_art.withdrawn_at is null and v_org.subscription_status not in('suspended','canceled');v_reason:=case when v_allowed then 'authorized' else 'grant expired, revoked, unaccepted, unverified, withdrawn, suspended, or outside scope' end;if v_grant.id is not null and v_art.id is not null then insert into public.evidence_guest_access_events(organization_id,facility_id,guest_grant_id,collection_id,artifact_id,event_type,request_fingerprint_sha256,reason)values(v_grant.organization_id,v_grant.facility_id,v_grant.id,v_grant.collection_id,v_art.id,case when v_allowed then p_event_type else 'denied' end,p_fingerprint,v_reason);end if;if not v_allowed then return jsonb_build_object('authorized',false,'reason','access_denied');end if;return jsonb_build_object('artifactId',v_art.id,'displayName',v_art.display_name,'scope',v_art.artifact_scope,'authorized',true);end$$;

create or replace function app_private.prevent_phase5_report_evidence_mutation() returns trigger language plpgsql set search_path='' as $$begin raise exception 'Report and external access evidence is append-only' using errcode='55000';end$$;
do $$declare t text;begin foreach t in array array['report_snapshots','historical_metric_snapshots','evidence_guest_access_events'] loop execute format('create trigger prevent_evidence_mutation before update or delete on public.%I for each row execute function app_private.prevent_phase5_report_evidence_mutation()',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['saved_report_definitions','saved_report_versions','report_schedules','report_snapshots','report_snapshot_artifacts','historical_metric_snapshots','evidence_collections','evidence_collection_artifacts','evidence_guest_grants','evidence_guest_access_events','evidence_guest_comments'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy reports_select on public.saved_report_definitions for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()));
create policy report_versions_select on public.saved_report_versions for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()));
create policy report_snapshots_select on public.report_snapshots for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and ((select public.current_role()) in('org_admin','auditor') or facility_id is not null and public.is_assigned_to_facility(facility_id)));
create policy report_artifacts_select on public.report_snapshot_artifacts for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and ((select public.current_role()) in('org_admin','auditor') or facility_id is not null and public.is_assigned_to_facility(facility_id)));
create policy evidence_collections_select on public.evidence_collections for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and ((select public.current_role()) in('org_admin','auditor') or public.is_assigned_to_facility(facility_id)));
create policy evidence_artifacts_select on public.evidence_collection_artifacts for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and ((select public.current_role()) in('org_admin','auditor') or public.is_assigned_to_facility(facility_id)));
create policy evidence_grants_select on public.evidence_guest_grants for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and (select public.current_role()) in('org_admin','auditor'));
create policy evidence_events_select on public.evidence_guest_access_events for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and (select public.current_role()) in('org_admin','auditor'));
do $$declare t text;begin foreach t in array array['saved_report_definitions','saved_report_versions','report_schedules','report_snapshots','report_snapshot_artifacts','historical_metric_snapshots','evidence_collections','evidence_collection_artifacts','evidence_guest_grants','evidence_guest_access_events','evidence_guest_comments'] loop execute format('revoke all on table public.%I from public,anon,authenticated,service_role',t);execute format('grant all on table public.%I to service_role',t);end loop;end$$;
grant select on public.saved_report_definitions,public.saved_report_versions,public.report_snapshots,public.report_snapshot_artifacts,public.evidence_collections,public.evidence_collection_artifacts,public.evidence_guest_grants,public.evidence_guest_access_events to authenticated;
revoke all on function public.record_report_snapshot(uuid,uuid,timestamptz,jsonb,jsonb,jsonb,jsonb,text,jsonb),public.issue_evidence_guest_grant(uuid,text,text,uuid[],timestamptz,boolean),public.authorize_evidence_guest_artifact(text,uuid,text,text) from public,anon,authenticated,service_role;
grant execute on function public.record_report_snapshot(uuid,uuid,timestamptz,jsonb,jsonb,jsonb,jsonb,text,jsonb) to service_role;
grant execute on function public.issue_evidence_guest_grant(uuid,text,text,uuid[],timestamptz,boolean) to authenticated;
grant execute on function public.authorize_evidence_guest_artifact(text,uuid,text,text) to anon,authenticated;

create or replace function public.get_closed_loop_compliance_control_plane() returns jsonb language sql stable security invoker set search_path='' as $$select jsonb_build_object(
'work',jsonb_build_object('open',(select count(*) from public.work_items where state in('open','in_progress','blocked')),'overdue',(select count(*) from public.work_items where state not in('closed','canceled') and due_at<now()),'urgent',(select count(*) from public.work_items where state not in('closed','canceled') and priority='urgent'),'pendingApproval',(select count(*) from public.work_items where state='pending_approval')),
'incidents',jsonb_build_object('awaitingTriage',(select count(*) from public.confidential_incident_intakes where status='submitted'),'investigating',(select count(*) from public.confidential_incident_intakes where status in('triage','investigating','review')),'critical',(select count(*) from public.confidential_incident_intakes where severity='critical' and status<>'closed')),
'moveIns',jsonb_build_object('active',(select count(*) from public.move_in_workspaces where state='active'),'ready',(select count(*) from public.move_in_workspaces where state='ready'),'openTasks',(select count(*) from public.move_in_tasks where state not in('approved','completed')),'activeGuests',(select count(*) from public.move_in_guest_grants where revoked_at is null and expires_at>now())),'reports',jsonb_build_object('saved',(select count(*) from public.saved_report_definitions),'scheduled',(select count(*) from public.report_schedules where enabled),'reconciledSnapshots',(select count(*) from public.report_snapshots where reconciliation_status='reconciled'),'varianceSnapshots',(select count(*) from public.report_snapshots where reconciliation_status='variance')),'evidenceRoom',jsonb_build_object('publishedCollections',(select count(*) from public.evidence_collections where status='published'),'activeGuestGrants',(select count(*) from public.evidence_guest_grants where revoked_at is null and expires_at>now()),'deniedAccess',(select count(*) from public.evidence_guest_access_events where event_type='denied'),'legalHolds',(select count(*) from public.evidence_collections where legal_hold)),'generatedAt',now());$$;
revoke all on function public.get_closed_loop_compliance_control_plane() from public,anon;
grant execute on function public.get_closed_loop_compliance_control_plane() to authenticated,service_role;
