create extension if not exists pgcrypto with schema extensions;

create table public.work_item_templates (
 id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id) on delete cascade,
 template_key text not null, name text not null, source_type text not null check(source_type in ('violation','inspection','incident','near_miss','training_gap','exclusion_match','credential','policy','rule_exception','move_in')),
 default_priority text not null default 'normal' check(default_priority in ('low','normal','high','urgent')),
 due_interval interval not null default interval '7 days', required_evidence_types text[] not null default array[]::text[],
 approval_required boolean not null default false, escalation_after interval, default_owner_role text,
 state_machine jsonb not null default '{"states":["open","in_progress","pending_approval","closed","canceled"]}'::jsonb,
 is_active boolean not null default true, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique nulls not distinct(organization_id,template_key)
);
create table public.work_items (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
 facility_id uuid not null references public.facilities(id) on delete restrict, template_id uuid references public.work_item_templates(id) on delete restrict,
 source_type text not null, source_id uuid not null, deduplication_key text not null, title text not null, description text,
 owner_profile_id uuid references public.profiles(id), priority text not null check(priority in ('low','normal','high','urgent')),
 due_at timestamptz not null, state text not null default 'open' check(state in ('open','in_progress','blocked','pending_approval','closed','canceled')),
 closure_reason text, approved_by uuid references public.profiles(id), approved_at timestamptz, escalated_at timestamptz,
 recurrence_key text, recurrence_number integer not null default 1, root_cause text, effectiveness_review_due_at timestamptz, effectiveness_result text,
 created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), closed_at timestamptz,
 unique(organization_id,deduplication_key), check(state<>'closed' or closed_at is not null and closure_reason is not null)
);
create index work_items_queue_idx on public.work_items(organization_id,facility_id,state,due_at);
create table public.work_item_watchers(id uuid primary key default gen_random_uuid(),work_item_id uuid not null references public.work_items(id) on delete cascade,profile_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),unique(work_item_id,profile_id));
create table public.work_item_dependencies(id uuid primary key default gen_random_uuid(),work_item_id uuid not null references public.work_items(id) on delete cascade,depends_on_work_item_id uuid not null references public.work_items(id) on delete restrict,dependency_type text not null default 'blocks' check(dependency_type in ('blocks','relates_to')),created_at timestamptz not null default now(),unique(work_item_id,depends_on_work_item_id),check(work_item_id<>depends_on_work_item_id));
create table public.work_item_comments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,work_item_id uuid not null references public.work_items(id) on delete cascade,author_profile_id uuid references public.profiles(id),body text not null check(length(btrim(body)) between 1 and 10000),visibility text not null default 'internal' check(visibility in ('internal','guest')),created_at timestamptz not null default now());
create table public.work_item_evidence(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),work_item_id uuid not null references public.work_items(id) on delete cascade,evidence_type text not null,storage_bucket text,storage_path text,linked_record_type text,linked_record_id uuid,content_sha256 text check(content_sha256 is null or content_sha256 ~ '^[0-9a-f]{64}$'),submitted_by uuid references public.profiles(id),approved_by uuid references public.profiles(id),approved_at timestamptz,created_at timestamptz not null default now(),check((storage_path is not null)::int+(linked_record_id is not null)::int=1));
create table public.work_item_history(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),work_item_id uuid not null references public.work_items(id) on delete restrict,event_type text not null,prior_state text,resulting_state text,actor_profile_id uuid references public.profiles(id),reason text not null,evidence jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());

create table public.confidential_incident_intakes (
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),
 intake_number text not null unique default ('INT-'||upper(encode(extensions.gen_random_bytes(8),'hex'))),report_type text not null check(report_type in ('incident','near_miss','safety_concern')),
 reported_at timestamptz not null default now(),occurred_at timestamptz,immediate_danger boolean not null default false,severity text not null check(severity in ('low','moderate','high','critical')),
 reporter_mode text not null check(reporter_mode in ('anonymous','identified')),public_summary text not null,status text not null default 'submitted' check(status in ('draft','submitted','triage','investigating','review','closed','retained')),
 resume_secret_sha256 text not null check(resume_secret_sha256 ~ '^[0-9a-f]{64}$'),confirmation_token_sha256 text not null check(confirmation_token_sha256 ~ '^[0-9a-f]{64}$'),
 triage_work_item_id uuid references public.work_items(id),retention_until date,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.confidential_incident_details(id uuid primary key default gen_random_uuid(),intake_id uuid not null unique references public.confidential_incident_intakes(id) on delete cascade,organization_id uuid not null references public.organizations(id) on delete cascade,resident_id uuid references public.residents(id) on delete restrict,narrative text not null,location_detail text,investigation_findings text,root_cause text,regulatory_deadline_at timestamptz,witness_data jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.confidential_reporter_identities(id uuid primary key default gen_random_uuid(),intake_id uuid not null unique references public.confidential_incident_intakes(id) on delete cascade,organization_id uuid not null references public.organizations(id) on delete cascade,reporter_profile_id uuid references public.profiles(id),encrypted_contact jsonb not null default '{}',consent_to_contact boolean not null default false,created_at timestamptz not null default now());
create table public.confidential_incident_access_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),intake_id uuid not null references public.confidential_incident_intakes(id) on delete restrict,actor_profile_id uuid references public.profiles(id),event_type text not null check(event_type in ('view_summary','view_details','view_identity','download','disclose','status_change','denied')),purpose text not null,occurred_at timestamptz not null default now());
create table public.confidential_intake_attempts(id bigint generated always as identity primary key,ip_hash text not null check(ip_hash ~ '^[0-9a-f]{64}$'),facility_id uuid references public.facilities(id),success boolean not null,error_code text,created_at timestamptz not null default now());
create index confidential_intake_attempts_rate_idx on public.confidential_intake_attempts(ip_hash,created_at desc);

create table public.move_in_templates(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,version integer not null,definition jsonb not null check(jsonb_typeof(definition)='object'),is_active boolean not null default true,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),unique(organization_id,name,version));
create table public.move_in_workspaces(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),resident_id uuid not null references public.residents(id) on delete cascade,template_id uuid not null references public.move_in_templates(id) on delete restrict,target_move_in_date date not null,state text not null default 'active' check(state in ('active','ready','completed','canceled')),readiness_snapshot jsonb not null default '{}',created_by uuid references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(resident_id,template_id));
create table public.move_in_tasks(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),workspace_id uuid not null references public.move_in_workspaces(id) on delete cascade,task_key text not null,title text not null,owner_profile_id uuid references public.profiles(id),due_at timestamptz,depends_on_task_keys text[] not null default array[]::text[],requires_document boolean not null default false,requires_signature boolean not null default false,requires_approval boolean not null default false,state text not null default 'open' check(state in ('open','in_progress','submitted','approved','exception','completed')),document_id uuid references public.resident_documents(id),signature_evidence jsonb,approved_by uuid references public.profiles(id),approved_at timestamptz,exception_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(workspace_id,task_key));
create table public.move_in_guest_grants(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),workspace_id uuid not null references public.move_in_workspaces(id) on delete cascade,resident_id uuid not null references public.residents(id) on delete cascade,token_sha256 text not null unique check(token_sha256 ~ '^[0-9a-f]{64}$'),guest_label text not null,allowed_task_ids uuid[] not null default array[]::uuid[],expires_at timestamptz not null,terms_version text not null,accepted_at timestamptz,revoked_at timestamptz,created_by uuid references public.profiles(id),created_at timestamptz not null default now(),check(expires_at>created_at));
create table public.move_in_guest_access_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,facility_id uuid not null references public.facilities(id),guest_grant_id uuid not null references public.move_in_guest_grants(id) on delete restrict,workspace_id uuid not null references public.move_in_workspaces(id) on delete restrict,task_id uuid references public.move_in_tasks(id) on delete restrict,event_type text not null check(event_type in ('view','upload','comment','sign','denied','revoked')),ip_hash text,user_agent_hash text,occurred_at timestamptz not null default now());

create or replace function app_private.assert_phase5_manager(p_org uuid,p_fac uuid default null) returns void language plpgsql stable security definer set search_path='' as $$ begin if coalesce(auth.jwt()->>'role','')='service_role' or public.is_platform_admin() then return; end if; if auth.uid() is null or public.current_org_id()<>p_org or public.current_role() not in ('org_admin','facility_manager') or (p_fac is not null and public.current_role()='facility_manager' and not public.is_assigned_to_facility(p_fac)) then raise exception 'Phase 5 operation is outside caller scope' using errcode='42501'; end if; perform public.assert_identity_assurance('workforce_admin'); end $$;
revoke all on function app_private.assert_phase5_manager(uuid,uuid) from public,anon,authenticated,service_role;

create or replace function public.create_deduplicated_work_item(p_org uuid,p_fac uuid,p_template_key text,p_source_type text,p_source_id uuid,p_dedupe text,p_title text,p_description text,p_owner uuid,p_priority text,p_due_at timestamptz)
returns uuid language plpgsql security definer set search_path='' as $$ declare v_id uuid;v_template public.work_item_templates%rowtype; begin perform app_private.assert_phase5_manager(p_org,p_fac);select id into v_id from public.work_items where organization_id=p_org and deduplication_key=p_dedupe;if found then return v_id;end if;select * into v_template from public.work_item_templates where (organization_id=p_org or organization_id is null) and template_key=p_template_key and is_active order by organization_id nulls last limit 1; insert into public.work_items(organization_id,facility_id,template_id,source_type,source_id,deduplication_key,title,description,owner_profile_id,priority,due_at,created_by) values(p_org,p_fac,v_template.id,p_source_type,p_source_id,p_dedupe,btrim(p_title),p_description,p_owner,coalesce(p_priority,v_template.default_priority,'normal'),coalesce(p_due_at,now()+v_template.due_interval,now()+interval '7 days'),auth.uid()) returning id into v_id; insert into public.work_item_history(organization_id,facility_id,work_item_id,event_type,resulting_state,actor_profile_id,reason) values(p_org,p_fac,v_id,'created','open',auth.uid(),'Configured source created owned work'); return v_id; end $$;

create or replace function public.transition_work_item(p_work_item_id uuid,p_target_state text,p_reason text) returns boolean language plpgsql security definer set search_path='' as $$ declare v public.work_items%rowtype;v_template public.work_item_templates%rowtype;begin select * into v from public.work_items where id=p_work_item_id for update;if not found then raise exception 'Work item not found' using errcode='P0002';end if;perform app_private.assert_phase5_manager(v.organization_id,v.facility_id);select * into v_template from public.work_item_templates where id=v.template_id;if p_target_state not in ('open','in_progress','blocked','pending_approval','closed','canceled') or length(btrim(coalesce(p_reason,'')))<5 then raise exception 'Invalid work transition' using errcode='22023';end if;if p_target_state='closed' and (exists(select 1 from unnest(coalesce(v_template.required_evidence_types,array[]::text[])) r where not exists(select 1 from public.work_item_evidence e where e.work_item_id=v.id and e.evidence_type=r)) or exists(select 1 from public.work_item_dependencies d join public.work_items w on w.id=d.depends_on_work_item_id where d.work_item_id=v.id and d.dependency_type='blocks' and w.state<>'closed')) then raise exception 'Closure evidence or dependencies are incomplete' using errcode='55000';end if;update public.work_items set state=p_target_state,closure_reason=case when p_target_state='closed' then btrim(p_reason) else closure_reason end,closed_at=case when p_target_state='closed' then now() else null end,updated_at=now() where id=v.id;insert into public.work_item_history(organization_id,facility_id,work_item_id,event_type,prior_state,resulting_state,actor_profile_id,reason)values(v.organization_id,v.facility_id,v.id,'transition',v.state,p_target_state,auth.uid(),btrim(p_reason));return true;end $$;

create or replace function public.start_confidential_incident_intake(p_facility_id uuid,p_report_type text,p_occurred_at timestamptz,p_immediate_danger boolean,p_severity text,p_reporter_mode text,p_public_summary text,p_narrative text,p_resident_id uuid,p_encrypted_contact jsonb,p_resume_secret text,p_confirmation_token text)
returns jsonb language plpgsql security definer set search_path='' as $$declare v_fac public.facilities%rowtype;v_id uuid;v_number text;v_work uuid;begin select * into v_fac from public.facilities where id=p_facility_id;if not found or length(p_resume_secret)<24 or length(p_confirmation_token)<24 or length(btrim(coalesce(p_public_summary,'')))<5 or length(btrim(coalesce(p_narrative,'')))<10 then raise exception 'Confidential intake request is invalid' using errcode='22023';end if;insert into public.confidential_incident_intakes(organization_id,facility_id,report_type,occurred_at,immediate_danger,severity,reporter_mode,public_summary,status,resume_secret_sha256,confirmation_token_sha256,retention_until)values(v_fac.organization_id,v_fac.id,p_report_type,p_occurred_at,p_immediate_danger,p_severity,p_reporter_mode,btrim(p_public_summary),'submitted',encode(extensions.digest(convert_to(p_resume_secret,'utf8'),'sha256'),'hex'),encode(extensions.digest(convert_to(p_confirmation_token,'utf8'),'sha256'),'hex'),current_date+2555)returning id,intake_number into v_id,v_number;insert into public.confidential_incident_details(intake_id,organization_id,resident_id,narrative)values(v_id,v_fac.organization_id,p_resident_id,btrim(p_narrative));if p_reporter_mode='identified' then insert into public.confidential_reporter_identities(intake_id,organization_id,reporter_profile_id,encrypted_contact)values(v_id,v_fac.organization_id,auth.uid(),coalesce(p_encrypted_contact,'{}'));end if;if p_immediate_danger or p_severity in('high','critical') then insert into public.work_items(organization_id,facility_id,source_type,source_id,deduplication_key,title,description,priority,due_at,state,created_by)values(v_fac.organization_id,v_fac.id,'incident',v_id,'confidential-intake:'||v_id,'Urgent confidential incident triage','Protected details available only to authorized investigators',case when p_severity='critical' then 'urgent' else 'high' end,now()+case when p_severity='critical' then interval '15 minutes' else interval '4 hours' end,'open',auth.uid()) returning id into v_work;update public.confidential_incident_intakes set triage_work_item_id=v_work where id=v_id;insert into public.work_item_history(organization_id,facility_id,work_item_id,event_type,resulting_state,actor_profile_id,reason)values(v_fac.organization_id,v_fac.id,v_work,'created','open',auth.uid(),'Urgent confidential intake created triage work');end if;return jsonb_build_object('intakeNumber',v_number,'confirmationToken',p_confirmation_token,'urgentRoutingCreated',v_work is not null);end$$;

create or replace function public.resume_confidential_incident_intake(p_intake_number text,p_resume_secret text,p_public_summary text,p_narrative text)
returns boolean language plpgsql security definer set search_path='' as $$declare v public.confidential_incident_intakes%rowtype;begin select * into v from public.confidential_incident_intakes where intake_number=p_intake_number for update;if not found or v.resume_secret_sha256<>encode(extensions.digest(convert_to(p_resume_secret,'utf8'),'sha256'),'hex') or v.status not in('draft','submitted') then raise exception 'Intake resume denied' using errcode='42501';end if;update public.confidential_incident_intakes set public_summary=btrim(p_public_summary),updated_at=now() where id=v.id;update public.confidential_incident_details set narrative=btrim(p_narrative),updated_at=now() where intake_id=v.id;return true;end$$;

create or replace function app_private.prevent_phase5_evidence_mutation() returns trigger language plpgsql set search_path='' as $$begin raise exception 'Phase 5 evidence is append-only' using errcode='55000';end$$;
do $$declare t text;begin foreach t in array array['work_item_history','confidential_incident_access_events','move_in_guest_access_events'] loop execute format('create trigger prevent_evidence_mutation before update or delete on public.%I for each row execute function app_private.prevent_phase5_evidence_mutation()',t);end loop;end$$;

do $$declare t text;begin foreach t in array array['work_item_templates','work_items','work_item_watchers','work_item_dependencies','work_item_comments','work_item_evidence','work_item_history','confidential_incident_intakes','confidential_incident_details','confidential_reporter_identities','confidential_incident_access_events','confidential_intake_attempts','move_in_templates','move_in_workspaces','move_in_tasks','move_in_guest_grants','move_in_guest_access_events'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy work_templates_select on public.work_item_templates for select to authenticated using(organization_id is null or (select public.is_platform_admin()) or organization_id=(select public.current_org_id()));
create policy work_items_select on public.work_items for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and ((select public.current_role()) in('org_admin','auditor') or public.is_assigned_to_facility(facility_id) or owner_profile_id=(select auth.uid())));
create policy work_history_select on public.work_item_history for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and ((select public.current_role()) in('org_admin','auditor') or public.is_assigned_to_facility(facility_id)));
create policy incident_intakes_select on public.confidential_incident_intakes for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and (select public.current_role()) in('org_admin','auditor') or organization_id=(select public.current_org_id()) and public.is_assigned_to_facility(facility_id) and status<>'draft');
create policy incident_details_select on public.confidential_incident_details for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and (select public.current_role()) in('org_admin','auditor'));
create policy incident_access_select on public.confidential_incident_access_events for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and (select public.current_role()) in('org_admin','auditor'));
create policy movein_workspaces_select on public.move_in_workspaces for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and ((select public.current_role()) in('org_admin','auditor') or public.is_assigned_to_facility(facility_id)));
create policy movein_tasks_select on public.move_in_tasks for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and ((select public.current_role()) in('org_admin','auditor') or public.is_assigned_to_facility(facility_id)));
create policy movein_templates_select on public.move_in_templates for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()));
create policy movein_guest_grants_select on public.move_in_guest_grants for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and (select public.current_role()) in('org_admin','auditor'));
create policy movein_guest_events_select on public.move_in_guest_access_events for select to authenticated using((select public.is_platform_admin()) or organization_id=(select public.current_org_id()) and (select public.current_role()) in('org_admin','auditor'));
do $$declare t text;begin foreach t in array array['work_item_templates','work_items','work_item_watchers','work_item_dependencies','work_item_comments','work_item_evidence','work_item_history','confidential_incident_intakes','confidential_incident_details','confidential_reporter_identities','confidential_incident_access_events','confidential_intake_attempts','move_in_templates','move_in_workspaces','move_in_tasks','move_in_guest_grants','move_in_guest_access_events'] loop execute format('revoke all on table public.%I from public,anon,authenticated,service_role',t);execute format('grant all on table public.%I to service_role',t);end loop;end$$;
grant select on public.work_item_templates,public.work_items,public.work_item_history,public.confidential_incident_intakes,public.confidential_incident_details,public.confidential_incident_access_events,public.move_in_templates,public.move_in_workspaces,public.move_in_tasks,public.move_in_guest_grants,public.move_in_guest_access_events to authenticated;
revoke all on function public.create_deduplicated_work_item(uuid,uuid,text,text,uuid,text,text,text,uuid,text,timestamptz),public.transition_work_item(uuid,text,text) from public,anon,authenticated,service_role;
grant execute on function public.create_deduplicated_work_item(uuid,uuid,text,text,uuid,text,text,text,uuid,text,timestamptz),public.transition_work_item(uuid,text,text) to authenticated;
revoke all on function public.start_confidential_incident_intake(uuid,text,timestamptz,boolean,text,text,text,text,uuid,jsonb,text,text),public.resume_confidential_incident_intake(text,text,text,text) from public,anon,authenticated,service_role;
grant execute on function public.start_confidential_incident_intake(uuid,text,timestamptz,boolean,text,text,text,text,uuid,jsonb,text,text),public.resume_confidential_incident_intake(text,text,text,text) to service_role;
