-- This migration's version/name were recovered from the live database's
-- supabase_migrations.schema_migrations history (project xsqobvvreaovwibxwyvv), but Supabase's
-- migration tracking only stores the version and name of an applied migration, not its SQL text
-- -- so unlike the five migrations before this one (20260704190000-20260704230000), this file's
-- original content could not be reconstructed from any observable difference between the schema
-- this repo's other migrations produce and the schema currently live: every table, column,
-- function, trigger, index, and RLS policy found on the live database is already accounted for
-- by 20260704190000 through 20260704230000 plus everything already committed before them.
--
-- One concrete, currently-live gap WAS found during that reconstruction (all nine functions
-- added by the five migrations above still have their default EXECUTE grant to `anon`, the
-- same category of issue 20260704180605_revoke_public_grant_on_privileged_functions.sql fixed
-- for older functions) -- but since it's still present live today, fixing it now had to be a new
-- migration on top (see the one immediately after this file), not a rewrite of this slot's
-- unknown history.
--
-- Left intentionally as a no-op so the local migration sequence stays contiguous with what
-- schema_migrations records, without asserting SQL that cannot be verified against production.
select 1;
