-- Keep database-backed Help Center copy aligned with the current application surface.
-- These shared articles cover feature areas added after the original seed: state forms,
-- evidence rooms, confidential intake, closed-loop compliance, enterprise foundations,
-- and platform operations.
insert into public.help_articles (article_type, category, title, sort_order, content)
select v.article_type, v.category, v.title, v.sort_order, v.content
from (values
  ('faq', 'Operations & Evidence', 'What are State Forms and how do they fit with resident compliance?', 41, '{"answer":"State Forms tracks DHS forms and other regulator-facing packets from draft through review, signature, filing, and renewal reminders. For personal care home and assisted living workflows, it complements resident assessment tracking by keeping the form lifecycle, source labels, due dates, and generated prefill support in one place instead of burying those documents in general uploads."}'::jsonb),
  ('faq', 'Operations & Evidence', 'What is the Evidence Room?', 42, '{"answer":"Evidence Room lets authorized users assemble curated evidence collections for surveys, audits, corrective actions, or internal reviews. Instead of emailing sensitive files, you can group certificates, policies, incident files, inspection proof, and uploaded documents, then share them through a time-limited guest room link when an outside reviewer needs access."}'::jsonb),
  ('faq', 'Operations & Evidence', 'How are confidential safety reports handled?', 43, '{"answer":"Confidential Reports provide a protected intake path for sensitive safety concerns. Authorized reviewers triage each submission, manage protected identity details, link the concern to a formal incident or corrective action when appropriate, and preserve a separate review audit trail so the report is not exposed like an ordinary incident list item."}'::jsonb),
  ('faq', 'Operations & Evidence', 'What does Closed-Loop Compliance do?', 44, '{"answer":"Closed-Loop Compliance connects findings, corrective actions, responsible owners, due dates, supporting evidence, and verification status across incidents, violations, inspections, and recurring compliance work. It is the follow-through layer that proves a finding was corrected, not just logged."}'::jsonb),
  ('faq', 'Operations & Evidence', 'What is the Regulatory Crosswalk?', 45, '{"answer":"The Regulatory Crosswalk maps training requirements, policies, inspection topics, resident requirements, state forms, and evidence collections back to the regulations they support. Use it when someone asks why a workflow exists, which citation drives it, or where the supporting proof lives."}'::jsonb),
  ('faq', 'Operations & Evidence', 'What is the PCH / ALF Operations Snapshot?', 46, '{"answer":"The PCH / ALF Operations Snapshot is a focused command center for personal care homes and assisted living residences. It brings together census, assessment timeliness, medication authorization, inspections, incidents, open follow-ups, and other resident-facing compliance signals so managers can act before survey risk builds up."}'::jsonb),
  ('faq', 'Platform & Enterprise', 'What is Enterprise Foundation?', 47, '{"answer":"Enterprise Foundation covers the controls larger organizations need before rollout: identity domains, provisioning and integration foundations, billing or package entitlements, and organization-level governance settings. Org admins see their enterprise setup under /app/enterprise, while the CareMetric platform team monitors the cross-tenant foundation under /admin/enterprise."}'::jsonb),
  ('job_aide', 'Operations & Evidence', 'Route a State Form Through Review', 29, '{"summary":"Track a regulator-facing form from draft through signature, filing, and renewal follow-up.","audience":["org_admin","facility_manager"],"steps":["Go to State Forms.","Choose the facility or resident context for the form.","Create or open the form record and confirm the source label, due date, and renewal timing.","Use generated prefill support where available, then review the form content before signature.","Move the form through review, signature, and filed status as your process completes.","Watch renewal reminders and related alerts so the next cycle is not missed."],"tips":["Use State Forms for regulator-facing packets that need lifecycle tracking; use Documents for general supporting uploads."],"relatedRoute":{"label":"Go to State Forms","href":"/app/state-forms"}}'::jsonb),
  ('job_aide', 'Operations & Evidence', 'Build and Share an Evidence Room Collection', 30, '{"summary":"Package related compliance proof into a curated collection and share it safely with an outside reviewer.","audience":["org_admin","facility_manager","auditor"],"steps":["Go to Evidence Room.","Create a new evidence collection for the survey, audit, corrective action, or internal review.","Add the relevant certificates, policy versions, incident files, inspection records, documents, and other supporting artifacts.","Review the collection for completeness and remove anything that does not belong in the packet.","Generate a guest access link only when an outside reviewer needs it.","Share the time-limited link and regenerate a fresh one if the review window expires."],"tips":["Evidence Room is safer than emailing attachments because access can expire and every collection stays tied to its source records."],"relatedRoute":{"label":"Go to Evidence Room","href":"/app/evidence"}}'::jsonb),
  ('job_aide', 'Operations & Evidence', 'Review a Confidential Safety Report', 31, '{"summary":"Triage a protected intake submission and connect it to follow-up work without overexposing sensitive details.","audience":["org_admin","facility_manager","auditor"],"steps":["Go to Confidential Reports.","Open the intake that needs review.","Read the protected report details and confirm whether immediate action is required.","Update triage status and document review notes according to your organization policy.","Link the report to a formal incident or corrective action when it needs follow-up in the standard compliance workflow.","Keep identity details limited to authorized reviewers and rely on the audit trail for accountability."],"tips":["Use the regular Incidents module for reportable-event management after triage; keep confidential intake details restricted."],"relatedRoute":{"label":"Go to Confidential Reports","href":"/app/confidential-incidents"}}'::jsonb),
  ('job_aide', 'Operations & Evidence', 'Close the Loop on a Compliance Finding', 32, '{"summary":"Assign owners, attach proof, and verify completion for findings that need documented follow-through.","audience":["org_admin","facility_manager","auditor"],"steps":["Go to Closed-Loop Compliance.","Open the finding or corrective-action item that needs work.","Assign an owner and due date.","Attach supporting evidence as the correction is completed.","Update the status as work moves from open to in progress to ready for verification.","Verify completion once the evidence supports closure."],"tips":["Use Closed-Loop Compliance when a finding needs proof of correction, not just a note on the original record."],"relatedRoute":{"label":"Go to Closed-Loop Compliance","href":"/app/closed-loop-compliance"}}'::jsonb),
  ('job_aide', 'Operations & Evidence', 'Use the Regulatory Crosswalk During Survey Prep', 33, '{"summary":"Trace workflows, evidence, and operating records back to the citation they support.","audience":["org_admin","facility_manager","auditor"],"steps":["Go to Regulatory Crosswalk.","Search or filter for the citation, facility type, topic, or workflow you need to explain.","Review the linked training, policy, inspection, resident, state-form, and evidence references.","Open the related record when you need source proof or current status.","Use the crosswalk as a prep checklist before surveys, audits, and internal reviews."],"tips":["The crosswalk explains why a workflow exists; Evidence Room packages the proof when someone outside the team needs to review it."],"relatedRoute":{"label":"Go to Regulatory Crosswalk","href":"/app/regulatory-crosswalk"}}'::jsonb),
  ('job_aide', 'Operations & Evidence', 'Review the PCH / ALF Operations Snapshot', 34, '{"summary":"Use the operating snapshot to identify resident-facing and facility follow-up risks before they become survey findings.","audience":["org_admin","facility_manager","auditor"],"steps":["Go to PCH / ALF Operations.","Select the facility or organization view you need.","Review census, assessment timeliness, medication authorization, inspections, incidents, state-form follow-up, and open corrective work.","Open any overdue or high-risk item from the snapshot to update the source record.","Use the snapshot in leadership huddles and survey-prep reviews so resident-facing issues are not tracked separately from staff compliance."],"tips":["The snapshot is most useful when teams review it routinely, not only after an alert fires."],"relatedRoute":{"label":"Go to PCH / ALF Operations","href":"/app/pch-alr-operations"}}'::jsonb),
  ('job_aide', 'Platform & Enterprise', 'Check System Jobs and Delivery Logs', 35, '{"summary":"Confirm whether background jobs, notifications, and webhook deliveries are running as expected.","audience":["platform_admin"],"steps":["Go to the platform admin area.","Open System Jobs to review scheduled or manual background work.","Open Notification Delivery when a user says an email, text, digest, or in-app notification did not arrive.","Review status, timestamps, retry information, and error details before rerunning or escalating.","Document any follow-up in the related support ticket or operational record."],"tips":["Use delivery logs to verify what the platform attempted before asking a customer to recheck inboxes or phones."],"relatedRoute":{"label":"Go to System Jobs","href":"/admin/system-jobs"}}'::jsonb)
) as v(article_type, category, title, sort_order, content)
where not exists (
  select 1
  from public.help_articles h
  where h.article_type = v.article_type
    and h.title = v.title
);
