-- Storage for the auto-filled official PA DHS Reportable Incident Form PDF, generated by
-- generate-incident-state-form-pdf. Distinct from report_pdf_storage_bucket/path (the
-- CareMetric-native "Reportable Incident Report" from generate-incident-report-pdf) -- these are
-- two different documents on the same incident, stored in the same bucket under different paths.
alter table public.incidents
  add column state_form_pdf_storage_bucket text,
  add column state_form_pdf_storage_path text,
  add column state_form_pdf_generated_at timestamptz;

-- Write is service-role only (the edge function) -- no authenticated INSERT/UPDATE/DELETE policy,
-- matching "incident-reports read"'s no-direct-client-write posture. Read mirrors incidents_select
-- RLS exactly (including the parenthesization fixed in
-- 20260706181320_fix_incident_reports_storage_rls_precedence.sql) in case a client ever attempts a
-- direct signed-url read outside the edge function's own signed-url response.
create policy "incident-reports state form read" on storage.objects for select to authenticated using (
  bucket_id = 'incident-reports'
  and exists (
    select 1 from public.incidents i
    where i.state_form_pdf_storage_bucket = storage.objects.bucket_id
      and i.state_form_pdf_storage_path = storage.objects.name
      and (
        public.is_platform_admin()
        or (i.organization_id = (select public.current_org_id())
            and ((select public.current_role()) in ('org_admin','auditor')
                 or ((select public.current_role()) = 'facility_manager' and public.is_assigned_to_facility(i.facility_id))))
      )
  )
);
